-- ============================================================
-- E-COMMERCE SALES ANALYSIS
-- Database: ECommerce_DB
-- Purpose: Sales data setup, validation and analysis
-- ============================================================


-- ============================================================
-- 1. DATABASE & TABLE SETUP
-- ============================================================

CREATE DATABASE ECommerce_DB;

USE ECommerce_DB;

CREATE TABLE sales_data (
    transaction_id INT,
    customer_id INT,
    product_name VARCHAR(255),
    quantity INT,
    price_per_unit DECIMAL(10,2),
    total_revenue DECIMAL(10,2),
    city VARCHAR(100),
    status VARCHAR(50)
);


-- ============================================================
-- 2. VALID SALES RECORDS
-- ============================================================
-- Retrieve only successful/valid sales transactions.

SELECT *
FROM sales_data
WHERE status = 'OK';


-- ============================================================
-- 3. REVENUE BY CITY
-- ============================================================
-- Calculate total revenue generated by each city.
-- Only valid sales transactions are included.

SELECT
    city,
    SUM(total_revenue) AS total_city_revenue
FROM sales_data
WHERE status = 'OK'
GROUP BY city
ORDER BY total_city_revenue DESC;


-- ============================================================
-- 4. PRODUCTS BY QUANTITY SOLD
-- ============================================================
-- Calculate the total quantity sold for each product.
-- Results are sorted from highest to lowest quantity.

SELECT
    product_name,
    SUM(quantity) AS total_quantity_sold
FROM sales_data
WHERE status = 'OK'
GROUP BY product_name
ORDER BY total_quantity_sold DESC;
